name: ðŸš€ Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    uses: cabinet-ceipi/infra-devops-pipelines/.github/workflows/build-backend-manual.yml@main
    with:
      dockerfile: ./Dockerfile
      context: .
